################################
# API Manager
autodiscoveryId: "20836042"

# Listener
https:
  port: "443"
################################

google:
  auth:
    host: "oauth2.googleapis.com"
    port: "443"
    path: "/token"
  calendars:
    host: "www.googleapis.com"
    port: "443"
    path: "/calendar/v3/calendars/primary/events"